numpy/numpy-financial

numpy_financial/_financial.py
numpy_financial/tests/test_financial.py

In particular,
- Handle arrays of rates that contain zero rates
- Fix handling of zero rates
- Avoid division by zero since `np.where` requires eager evaluation
Closes gh-16, closes gh-18.

BUG: fix some issues with `nper`

---

numpy_financial/_financial.py
numpy_financial/tests/test_financial.py

As stated in the the docs the period count starts at 1, so `per < 1`
doesn't make sense. The change also agrees with the results of Google
Sheet's IPMT.
Closes gh-17. Note that the suggested fix there appears to be
incorrect-returning `0` for `when = 'begin'` and `per = 1` should
be the correct behavior as no interest has accrued at the beginning
of the first period. (Returning 0 also agrees with IPMT.)

BUG: make `ipmt` return `nan` for `per < 1`

---

numpy_financial/_financial.py
numpy_financial/tests/test_financial.py

In particular, more clearly divide the rate-is-zero versus
rate-is-nonzero cases. Also organize the tests and add test cases for
broadcasting and zero rate.
I find implementing `fv` it this way much easier to understand, but if
others disagree I'm happy to drop it.

MAINT: clean up the implementation of `fv`

---

numpy_financial/_financial.py
numpy_financial/tests/test_financial.py

NumPy's roots function uses the companion matrix to find polynomial
roots. In the process it makes the polynomial monic by dividing by the
leading coefficient, which can cause overflow/underflow. This can be
avoided by working with a scaled version of the companion matrix
instead. Since scaling the matrix simply scales the eigenvalues
(i.e. the roots of the polynomial in this case), the original roots
can easily be recovered.
Closes gh-15.

BUG: prevent underflow/overflow when finding roots in IRR

---

numpy_financial/_financial.py
numpy_financial/tests/test_financial.py

In particular,
- Avoid shadowing the function name with an `ipmt` variable inside the
function
- Ensure that the function returns a scalar for 0d inputs; add
regression tests
- Move some tests into the `TestIpmt` class that were missed in the
previous refactoring

MAINT: small cleanups to `ipmt`

---

numpy_financial/tests/test_financial.py

In particular,
- Move them into their own class
- Add tests for invalid `per` arguments
First mentioned in https://github.com/numpy/numpy-financial/pull/22.

TST: clean up `ppmt` tests

---

.github/workflows/pythonpackage.yml
setup.py

https://github.com/numpy/numpy-financial/pull/49 fails because Python 3.5 is no longer supported by Github actions. This PR removes Python 3.5 from the tests. They are now only running with Python 3.6 and 3.7.

TEST: Drop python 3.5 tests

---

numpy_financial/_financial.py
numpy_financial/tests/test_financial.py

This PR changes ``rate`` to return results for all solutions found that are within `tol` rather than returning `nan` if any of the results are found.  For example on master running:
```python
import numpy_financial as npf
pv = [-593.06, -4725.38, -662.05, -428.78, -13.65]
fv = [214.07, 4509.97, 224.11, 686.29, -329.67]
print(npf.rate(2, 0, pv, fv))
```
returns 
```[nan nan nan nan nan]```
the same code now returns
```[-0.39920185 -0.02305873 -0.41818459  0.26513414         nan]```
This PR closes gh-48

ENH: Return close results in rate calculation

---

numpy_financial/_financial.py
numpy_financial/tests/test_financial.py

This PR uses Netwon's method to calculate the IRR instead of the existing eigenvalue approach.
The most significant difference is that now only the root closest to `guess` is found, not all of the roots. This means IRR no longer has to decided which root to return to the user. For large inputs this is significantly faster. On my system all tests pass but, so far, this is only a proof of concept and I'll still need to consider if there are any unforeseen changes.
@jamiecook - how does this look to you? It's using an initial guess, but, in this case, the guess serves a purpose as the initial solution in Newton's method.

ENH: Use Newton's method to calculate IRR

---

numpy_financial/_financial.py
numpy_financial/tests/test_financial.py

This PR applies broadcasting operations to ``npv`` calculations. This is significantly faster than iterating over an array of cashflows as is shown by the below code snippet.
```python
import numpy as np
from numpy.testing import assert_allclose
import numpy_financial as npf
import time
def faster_npv(rate: float, values: np.ndarray):
""" A faster way to calculate NPV for several projects based
on numpy arrays. """
values = np.atleast_2d(values)
timestep_array = np.arange(0, values.shape[1])
npv = (values / (1 + rate) ** timestep_array).sum(axis=1)
try:
return npv.item()
except ValueError:
return npv
if __name__ == "__main__":
rate = 0.05
no_simulations = int(1e6)
lifetime = 10  # years
capex = np.random.normal(loc=1000, scale=100, size=no_simulations)
opex = np.random.normal(loc=100, …
```

ENH: Allow npv calculation to be broadcastable

---

.github/workflows/pythonpackage.yml

The test matrix was last updated in 2019. Using versions of NumPy and Python that have reached their end of life. This commit bumps the versions used to those that are still within their lifetime.

TST/MAINT: Update CI scirpts

---

numpy_financial/_financial.py

The IRR computation adds and then subtract the previous iteration value before comparing to the tolerance. We can just compute the delta and compare that to the tolerance instead. This should also make the computation more robust if there is a large difference in magnitude between `x` and `delta`

Avoid redundant computations in IRR calculation

---

numpy_financial/_financial.py
numpy_financial/tests/test_financial.py

**Reference Issues/PRs**
None
**What does this implement?**
Small addition to the IRR function, such that it prints it is returning np.nan when all the cashflows are of the same sign. This will make the function more user intuitive, since the user will know why the function is returning nans and will make him check if the cashflows were properly calculated.
**Any other comment?**
Instead of a print, I'd use a warnings.warn, but for that the warnings package is needed, and I believe you want to minimize the requirements.txt

Small addition to IRR function

---

.github/workflows/lint.yml
.github/workflows/pythonpackage.yml

This removes the redundancy of running the linting for each combination of OS/Python version

TST: Make linting own step in CI pipeline

---

.github/workflows/pythonpackage.yml

This commit tests against the newest version of Python, 3.12

MAINT: Test against Python 3.12

---

doc_developer/getting_the_code.md

This explains to developers how to access the NumPy-Financial source code using git.

DOC: First draft to help getting the code

---

tests/test_financial.py

parametrize tests

---

numpy_financial/_financial.py

This parameter will be added as a new parameter, I think it is more descriptive to have keyword only parameters for non-essential params.

MAINT: Make `guess` parameter keyword only

---

.gitignore
doc/source/conf.py
pyproject.toml

This applies the pydata_sphinx_theme theme to NumPy Financial. The theme builds and the documentation is rendered _almost_ correctly, except that LaTeX is rendered to the far right of the page.

Initial change to pydata_sphinx_theme

---

.github/workflows/lint.yml
numpy_financial/__init__.py
numpy_financial/_financial.py
pyproject.toml
tests/test_financial.py

Ruff is an extremely fast and comprehensive linter.
Note that `ANN` (annotations) has been ignored intentionally, as they do not exist yet. This will be rectified later in the work.

CI/STY: Move to Ruff

---

.github/workflows/lint.yml
tests/test_financial.py

This PR adds ruff to run on the test file and fixes several style issues.

MAINT: Run ruff on test file

---

.github/workflows/lint.yml
benchmarks/benchmarks.py

This PR adds style checking for benchmarks in the CI pipeline.

CI/BENCH: Add style checks for benchmarks

---

doc/source/doc_developer/building_with_poetry.rst
doc/source/doc_developer/getting_the_code.rst
doc/source/index.rst

Set up development docs as rst files

---

numpy_financial/_financial.py

This pull request addresses issue #76 by enhancing the documentation for the `mirr` function. 
I have updated the docstring to provide clearer explanations of the function's purpose, parameters, and usage. Additionally, I incorporated a more detailed MIRR formula, including the reinvestment rate, and provided illustrative examples to guide users in understanding how to use the function effectively.

Updating mirr docstring [issue 76]

---

.github/workflows/pythonpackage.yml
benchmarks/benchmarks.py
numpy_financial/_financial.py
pyproject.toml
tests/test_financial.py

NumPy-Financial now supports calculation of NPV for vectors of rates and cashflows e.g.
```python
>>> rates = [0.00, 0.05, 0.10]
>>> cashflows = [[-4_000, 500, 800], [-5_000, 600, 900]]
>>> npf.npv(rates, cashflows)
array([[-2700.  , -3500.  ],
[-2798.19, -3612.24],
[-2884.3 , -3710.74]])
```
This was previously not supported. This behaviour was first implemented by naively looping through rates and values. As Python for loops are slow, numba is applied to accelerate the process. This has lead to a significant speedup, especially for native types.
There are some potential drawbacks to using numba:
* It adds another dependency to our stack
* That dependency is large (>100MB)
* numba requires a runtime step to compile
*  We need to duplicate the functions for `Decimal` support

ENH: NPV: Support calculation for vectors of rates and cashflows

---

.github/workflows/pythonpackage.yml
benchmarks/benchmarks.py
numpy_financial/_financial.py
pyproject.toml
tests/test_financial.py

The `--doctest-modules` option of pytest is added to the original `poetry run pytest` for testing the documentation code examples.

Add automated documentation testing when building

---

tests/test_financial.py

#66 Fixed the issue.
Changed assert_almost_equals to assert_allclose and a custom function(assert_decimal_close).
Had to create assert_decimal_close, which finds the absolute difference in values and compares it to a tolerance level.
Cannot use the assert_allclose because it uses infinite under the covers which does not support the Decimal type.
See issue: https://github.com/numpy/numpy/issues/9954
In addition, ran ruff format test_financial.py

Removed all instances of assert_almost_equal

---

.github/workflows/pythonpackage.yml
benchmarks/benchmarks.py
numpy_financial/_financial.py
pyproject.toml
tests/test_financial.py

This pull request removes my previously completed work to add numba to numpy-financial.
It will not be used as the ufunc rework is no longer being completed and integration with `decimal.Decimal` is not yet where it needs to be for us to use it,

REV: Remove numba

---

.github/workflows/pythonpackage.yml
pyproject.toml

This PR changes several of the minimum required dependencies. 
Most notable is the bump from Python 3.9 to 3.10 as the minimum supported version. Python 3.10 adds several new features, including typing improvements and the match statement.

REL: Update minimum required versions

---

doc_developer/running_the_benchmarks.md

This commit adds a new file in the developer documentation for how to run NumPy-Financial's benchmark suite.

DOC: Add developer documentation for benchmarking

---

benchmarks/benchmarks.py
numpy_financial/_financial.py
pyproject.toml
tests/test_financial.py

This commit reworks the ``npv`` function to mimic broadcasting. behaviour.
It also:
* drops support for ``decimal.Decimal`` in npv.
* introduces [Hypothesis](https://hypothesis.readthedocs.io/en/latest/) for testing

ENH: npv: Rework npv function to mimic broadcasting

---

doc_developer/building_the_docs.md

This PR documents how to build the NumPy-Financial documentation and website.
closes #89

DOC: docs: Document how to build the documentation

---

numpy_financial/_cfinancial.pyx
numpy_financial/_financial.py
numpy_financial/tests/test_financial.py

This PR mimics broadcasting for ``nper`` it also enhances the performance using Cython

ENH: nper: broadcast rework with Cython

---

numpy_financial/_financial.py

IRR function was changed to accept 2D-arrays as input. A for-loop was included to iterate over 
each row of the array, generate an IRR, and append its value to a results array.

Altered IRR function to accept 2D-array

---

numpy_financial/_financial.py

Logic for selection of IRR when more than 1 real value is found was refactored into a separate function, allowing for user customisation of selection logic if required.

Refactor selection logic for IRR 

---

.github/workflows/pythonpackage.yml
environment.yml
numpy_financial/_financial.py
numpy_financial/tests/strategies.py
numpy_financial/tests/test_financial.py

This changes the environment name to `npf-dev` and removes the duplicate entry for asv.

MAINT: Tidy up environment.yml

---

pyproject.toml

This resolves the following Python 3..13 build-time warning:
```
********************************************************************************
Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
By 2026-Feb-18, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
********************************************************************************
```
See also
- <https://peps.python.org/pep-0639/>
- <https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license>

MAINT: use a PEP 639 ``project.license`` SPDX expression

---

.github/workflows/type_check.yml
numpy_financial/_cfinancial.pyi
numpy_financial/_financial.py
numpy_financial/meson.build
pyproject.toml

I intentionally annotated the input types to (also) accept the overly-loose `numpy.typing.ArrayLike` type. Because even though that also accepts invalid input, it would avoid breaking user code like
```py
def get_rich_quick(p: npt.ArrayLike):
r = npf.irr(p)
return profit
```
which I'm guessing is the primary use-case of `numpy_financial` (or maybe that was just me).
Anyway, there's still quite a bit of room for improvement. For example, by making `mypy` and `pyright` pass is strict mode. But getting there wll take quite a bit of effort for diminishing returns.
---
Closes #133

TYP: Inline typing annotations
